config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'neighborhoods#index'

  resources :neighborhoods, only: :index do
    resources :bars
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bar.rb
class Bar < ApplicationRecord
  belongs_to :neighborhood

  validates :name,:specialty_drink, presence: true
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  has_many :bars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  def index
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    # @bars = Bar.where(neighborhood_id: @neighborhood.id)
    @bars = @neighborhood.bars
  end

  def show
    @bar = Bar.find(params[:id])
  end

  def new
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @bar = Bar.new
  end

  def edit
  end

  def create
    @bar = Bar.new(bar_params)
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @bar.neighborhood = @neighborhood
    if @bar.save
      if request.xhr?
        render json: @bar
      else
        redirect_to neighborhood_bar_path(@neighborhood, @bar)
      end
    else
      @errors = @bar.errors.full_messages
      render 'new'
    end
  end

  def update
  end

  private
  def bar_params
    params.require(:bar).permit(:name, :specialty_drink, :cash_only)
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  def index
    @neighborhoods = Neighborhood.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bars/index.html.erb
<h1>Bars yo</h1>

<%= link_to "Add a bar", new_neighborhood_bar_path(@neighborhood) %>

<% @bars.each do |bar| %>
  <p><%= link_to bar.name, neighborhood_bar_path(@neighborhood, bar) %></p>
<% end %>

app/views/bars/new.html.erb
<% if @errors %>
  <% @errors.each do |err| %>
    <p><%= err %></p>
  <% end %>
<% end %>

<%= form_for [:neighborhood, @bar], remote: true, id: 'formy' do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :specialty_drink %>
  <%= f.text_field :specialty_drink %><br>

  <%= f.label :cash_only %>
  <%= f.select :cash_only, options_for_select([true,false]) %><br>

  <%= f.submit %>
<% end %>

app/views/bars/show.html.erb
<p>Name: <%= @bar.name %></p>
<p>Specialty Drink: <%= @bar.specialty_drink %></p>
<p>Cash Only: <%= @bar.cash_only %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Neighbar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/neighborhoods/index.html.erb
<h1>Neighbar</h1>

<h3>Neighborhoods</h3>
<% @neighborhoods.each do |neigh| %>
  <p><%= link_to neigh.name, neighborhood_bars_path(neigh) %></p>
<% end %>